accent = "#626870"
cursor = "#2A2B26"
foreground = "#2A2B26"
background = "#BCBDC1"
selection_foreground = "#BCBDC1"
selection_background = "#474A4F"

color0 = "#2A2B26"
color1 = "#7A3328"
color2 = "#4F7A3A"
color3 = "#8B7A30"
color4 = "#4A6080"
color5 = "#804A6E"
color6 = "#3A7A72"
color7 = "#E1E2E7"
color8 = "#666870"
color9 = "#943D2E"
color10 = "#608A48"
color11 = "#A08A40"
color12 = "#587090"
color13 = "#905880"
color14 = "#488A82"
color15 = "#EDEEF3"
